version: "3.1"
services:
    www:
        build: .
        ports: 
            - "8001:80"
        environment:
            DBHOST: ${DBHOST}
            DBNAME: ${DBNAME}
            DBUSERNAME: ${DBUSERNAME}
            DBPASSWORD: ${DBPASSWORD}
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: ${DBNAME}
            MYSQL_USER: ${DBUSERNAME}
            MYSQL_PASSWORD: ${DBPASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
        volumes:
            - ./db_dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: ${DBUSERNAME}
            MYSQL_PASSWORD: ${DBPASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
volumes:
    persistent: